### ISSUE TITLE
Duplicate "typeCoverage" keys in package.json file

### ISSUE THREAD

**Issue by gregmagolan** [wooorm/decode-named-character-reference#2]
This causes parsing issues with strict JSON parsers such as Bazel's used in rules_js https://github.com/aspect-build/rules_js/blob/dacb4c58dbca319b0a1e58a426dc7bbd39c76e56/js/private/npm_import.bzl#L274.

Error is similar to the one in https://github.com/wooorm/stringify-entities/issues/11 which also has the same duplicate key.

**Comment by wooorm** [comment]
Thanks, [released](https://github.com/wooorm/decode-named-character-reference/releases/tag/1.0.2). I’d imagine it better for your tools to accept things that are valid on npm tho
