### ISSUE TITLE
I try to use mdx in react native, but this package needs document.createElement, is there any way to solve it?

### ISSUE THREAD

**Issue by zfben** [wooorm/decode-named-character-reference#3]

**Comment by wooorm** [comment]
This package only uses DOM APIs when some tool you are using specifically says it is a browser and not react-native: https://github.com/wooorm/decode-named-character-reference/blob/4347630741f82d7d4c7fb38763ba158951b2a1be/package.json#L32-L40.

**Comment by amritk** [comment]
How does it decide? Currently I am using it on the server but its being called by `remark-parse` and `remark-stringify` Is there any flag/env var I can set on my end so it gets the correct one?
