### ISSUE TITLE
Package does not load the correct source file in a Worker

### ISSUE THREAD

**Issue by spmonahan** [wooorm/decode-named-character-reference#4]
I've created a repro repo here: https://github.com/spmonahan/decode-named-character-reference-worker-webpack-bug

The issue is that when I try to use Remark in a Worker the DOM version of `decode-named-character-reference` is being loaded despite [the worker export being configured](https://github.com/wooorm/decode-named-character-reference/blob/main/package.json#L36) in this package.

[According to Webpack's docs the `worker` export is supported](https://webpack.js.org/guides/package-exports/#target-environment) and while this might be a Webpack bug I wanted to raise it here in case it's a package configuration issue.

**Comment by spmonahan** [comment]
Actually, looks like this is a Webpack issue: https://github.com/webpack/webpack/issues/17512

**Comment by aFcFzF** [comment]
this my resolve in webpack:

// resolve document in worker
const decodePath = require.resolve('decode-named-character-reference');
const decodeDir = path.dirname(decodePath); // 提取模块所在目录


config.resolve.alias = {
     'decode-named-character-reference$': path.join(decodeDir, 'index.js'),
}
